# Generated by Django 5.0.1 on 2024-01-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openstockmate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StokPage',
        ),
    ]
